apiVersion: apps/v1
kind: Deployment
metadata:
  name: restimage-deployment
  labels:
    app: restimage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restimage
  template:
    metadata:
      labels:
        app: restimage
    spec:
      containers:
      - name: restimage 
        image: rdanimt/restimage:latest
        ports:
        - containerPort: 8000
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: restimage-rollout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restimage
  strategy:
    blueGreen:
      activeService: rdanimt-restimage
      previewService: rdanimt-restimage-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: restimage
    spec:
      containers:
      - name: restimage 
        image: rdanimt/restimage:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rdanimt-restimage
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: restimage
---
apiVersion: v1
kind: Service
metadata:
  name: rdanimt-restimage-preview-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: restimage
    
