apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: restimage-deployment 
  labels:
    app: restimage
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: restimage
  template: 
    metadata: 
      labels:
        app: restimage
    spec:
      containers:
        - name: restimage 
          image: rdanimt/restimage:latest
          ports:
          - containerPort: 8000
